
package com.example.la.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CountryInfoPortType", targetNamespace = "http://www.oorsprong.org/websamples.countryinfo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountryInfoPortType {


    /**
     * 
     * @return
     *     returns com.example.la.soap.ArrayOfContinents
     */
    @WebMethod(operationName = "ListOfContinentsByName", action = "http://www.oorsprong.org/websamples.countryinfo/ListOfContinentsByName")
    @WebResult(name = "ListOfContinentsByNameResult", targetNamespace = "")
    @RequestWrapper(localName = "ListOfContinentsByName", targetNamespace = "http://www.oorsprong.org/websamples.countryinfo", className = "com.example.la.soap.ListOfContinentsByNameType")
    @ResponseWrapper(localName = "ListOfContinentsByNameResponse", targetNamespace = "http://www.oorsprong.org/websamples.countryinfo", className = "com.example.la.soap.ListOfContinentsByNameResponseType")
    public ArrayOfContinents listOfContinentsByName();

    /**
     * 
     * @return
     *     returns com.example.la.soap.ArrayOfCountryNames
     */
    @WebMethod(operationName = "ListOfCountryNamesByName", action = "http://www.oorsprong.org/websamples.countryinfo/ListOfCountryNamesByName")
    @WebResult(name = "ListOfCountryNamesByNameResult", targetNamespace = "")
    @RequestWrapper(localName = "ListOfCountryNamesByName", targetNamespace = "http://www.oorsprong.org/websamples.countryinfo", className = "com.example.la.soap.ListOfCountryNamesByNameType")
    @ResponseWrapper(localName = "ListOfCountryNamesByNameResponse", targetNamespace = "http://www.oorsprong.org/websamples.countryinfo", className = "com.example.la.soap.ListOfCountryNamesByNameResponseType")
    public ArrayOfCountryNames listOfCountryNamesByName();

}
